#!/bin/bash


export PLATFORM_VERSION=11
export ANDROID_MAJOR_VERSION=r
export ARCH=arm64
export KBUILD_BUILD_USER=Ramen
export KBUILD_BUILD_HOST=SUSANO
export SUBARCH=arm64
export PATH="/home/_123/KERNEL/clang-r416183b1/bin:$PATH"
export CC=clang
export LLVM=1
export LLVM_IAS=0
export CROSS_COMPILE=aarch64-linux-gnu-
export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
export LD=ld.lld
export AR=llvm-ar
export NM=llvm-nm
export OBJCOPY=llvm-objcopy
export OBJDUMP=llvm-objdump
export READELF=llvm-readelf
export OBJSIZE=llvm-size
export STRIP=llvm-strip
export LDGOLD=aarch64-linux-gnu-ld.gold
export LLVM_AR=llvm-ar
export LLVM_DIS=llvm-dis
make m21_defconfig
make -j16
