#!/bin/bash


export PLATFORM_VERSION=11
export ANDROID_MAJOR_VERSION=r
export ARCH=arm64
export KBUILD_BUILD_USER=Ramen
export KBUILD_BUILD_HOST=SUSANO
export SUBARCH=arm64
export ANDROID_MAJOR_VERSION=q
export PATH="/home/_123/KERNEL/gcc-arm64/bin:$PATH"
export CC=gcc
export CROSS_COMPILE=aarch64-elf-
make m21_defconfig
make -j16
